# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pydantic_ai_runtime._proto.eaasp.runtime.v2 import hook_pb2 as eaasp_dot_runtime_dot_v2_dot_hook__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eaasp/runtime/v2/hook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HookBridgeServiceStub(object):
    """============================================================
    EAASP v2.0 — HookBridge Service
    ============================================================

    L1 Runtime ↔ HookBridge bidirectional communication.
    Inherits the bidirectional streaming design from Phase BE W2,
    re-rooted on v2 common types.

    T1 Harness (grid-runtime) implements hooks in-process — does NOT
    need to talk to HookBridge. T2 Aligned / T3 Framework runtimes
    use this service to delegate hook evaluation to L3 governance.

    Bidirectional mode:
    L1 → HookBridge: hook events (pre_tool_call, post_tool_result, stop, ...)
    HookBridge → L1: hook decisions + optional policy update pushes

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamHooks = channel.stream_stream(
                '/eaasp.runtime.v2.HookBridgeService/StreamHooks',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookEvent.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookResponse.FromString,
                _registered_method=True)
        self.EvaluateHook = channel.unary_unary(
                '/eaasp.runtime.v2.HookBridgeService/EvaluateHook',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookEvaluateRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookDecision.FromString,
                _registered_method=True)
        self.ReportTelemetry = channel.unary_unary(
                '/eaasp.runtime.v2.HookBridgeService/ReportTelemetry',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookTelemetryBatch.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.TelemetryAck.FromString,
                _registered_method=True)
        self.GetPolicySummary = channel.unary_unary(
                '/eaasp.runtime.v2.HookBridgeService/GetPolicySummary',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.PolicySummaryRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.PolicySummary.FromString,
                _registered_method=True)


class HookBridgeServiceServicer(object):
    """============================================================
    EAASP v2.0 — HookBridge Service
    ============================================================

    L1 Runtime ↔ HookBridge bidirectional communication.
    Inherits the bidirectional streaming design from Phase BE W2,
    re-rooted on v2 common types.

    T1 Harness (grid-runtime) implements hooks in-process — does NOT
    need to talk to HookBridge. T2 Aligned / T3 Framework runtimes
    use this service to delegate hook evaluation to L3 governance.

    Bidirectional mode:
    L1 → HookBridge: hook events (pre_tool_call, post_tool_result, stop, ...)
    HookBridge → L1: hook decisions + optional policy update pushes

    """

    def StreamHooks(self, request_iterator, context):
        """Bidirectional stream: events in, decisions out, plus policy pushes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateHook(self, request, context):
        """One-shot evaluation for runtimes that don't maintain a persistent stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTelemetry(self, request, context):
        """Report hook execution telemetry back to HookBridge.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicySummary(self, request, context):
        """Fetch a summary of currently loaded policies for debugging.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HookBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamHooks': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamHooks,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookEvent.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookResponse.SerializeToString,
            ),
            'EvaluateHook': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateHook,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookEvaluateRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookDecision.SerializeToString,
            ),
            'ReportTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTelemetry,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookTelemetryBatch.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.TelemetryAck.SerializeToString,
            ),
            'GetPolicySummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicySummary,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.PolicySummaryRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_hook__pb2.PolicySummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eaasp.runtime.v2.HookBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eaasp.runtime.v2.HookBridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HookBridgeService(object):
    """============================================================
    EAASP v2.0 — HookBridge Service
    ============================================================

    L1 Runtime ↔ HookBridge bidirectional communication.
    Inherits the bidirectional streaming design from Phase BE W2,
    re-rooted on v2 common types.

    T1 Harness (grid-runtime) implements hooks in-process — does NOT
    need to talk to HookBridge. T2 Aligned / T3 Framework runtimes
    use this service to delegate hook evaluation to L3 governance.

    Bidirectional mode:
    L1 → HookBridge: hook events (pre_tool_call, post_tool_result, stop, ...)
    HookBridge → L1: hook decisions + optional policy update pushes

    """

    @staticmethod
    def StreamHooks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/eaasp.runtime.v2.HookBridgeService/StreamHooks',
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookEvent.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateHook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.HookBridgeService/EvaluateHook',
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookEvaluateRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.HookBridgeService/ReportTelemetry',
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.HookTelemetryBatch.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.TelemetryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicySummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.HookBridgeService/GetPolicySummary',
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.PolicySummaryRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_hook__pb2.PolicySummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
