# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pydantic_ai_runtime._proto.eaasp.runtime.v2 import common_pb2 as eaasp_dot_runtime_dot_v2_dot_common__pb2
from pydantic_ai_runtime._proto.eaasp.runtime.v2 import runtime_pb2 as eaasp_dot_runtime_dot_v2_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eaasp/runtime/v2/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """============================================================
    EAASP v2.0 — L1 Runtime Contract
    ============================================================

    Spec: docs/design/EAASP/EAASP-Design-Specification-v2.0.docx §8

    16 methods total:
    - 12 MUST (certified core, every conforming runtime implements)
    -  4 OPTIONAL (health / pause / disconnect / resume)
    -  1 PLACEHOLDER (EmitEvent — ADR-V2-001 pending)

    Runtime tiers:
    T1 Harness   — implements trait natively (zero serialization, e.g. grid-runtime)
    T2 Aligned   — implements via gRPC adapter (e.g. hermes-runtime-python, claude-code-runtime-python)
    T3 Framework — external agent framework wrapped by adapter

    ── 12 MUST methods (certifier verifies presence + passing tests) ──
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/Initialize',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.InitializeRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Send = channel.unary_stream(
                '/eaasp.runtime.v2.RuntimeService/Send',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.SendRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.SendResponse.FromString,
                _registered_method=True)
        self.LoadSkill = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/LoadSkill',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.LoadSkillRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.LoadSkillResponse.FromString,
                _registered_method=True)
        self.OnToolCall = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/OnToolCall',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolCallEvent.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolCallAck.FromString,
                _registered_method=True)
        self.OnToolResult = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/OnToolResult',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolResultEvent.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolResultAck.FromString,
                _registered_method=True)
        self.OnStop = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/OnStop',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StopEvent.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StopAck.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/GetState',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.FromString,
                _registered_method=True)
        self.ConnectMCP = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/ConnectMCP',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ConnectMCPRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ConnectMCPResponse.FromString,
                _registered_method=True)
        self.EmitTelemetry = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/EmitTelemetry',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/GetCapabilities',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.Capabilities.FromString,
                _registered_method=True)
        self.Terminate = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/Terminate',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.RestoreState = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/RestoreState',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/Health',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.DisconnectMcp = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/DisconnectMcp',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.DisconnectMcpRequest.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.PauseSession = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/PauseSession',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.FromString,
                _registered_method=True)
        self.ResumeSession = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/ResumeSession',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.EmitEvent = channel.unary_unary(
                '/eaasp.runtime.v2.RuntimeService/EmitEvent',
                request_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.EventStreamEntry.SerializeToString,
                response_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """============================================================
    EAASP v2.0 — L1 Runtime Contract
    ============================================================

    Spec: docs/design/EAASP/EAASP-Design-Specification-v2.0.docx §8

    16 methods total:
    - 12 MUST (certified core, every conforming runtime implements)
    -  4 OPTIONAL (health / pause / disconnect / resume)
    -  1 PLACEHOLDER (EmitEvent — ADR-V2-001 pending)

    Runtime tiers:
    T1 Harness   — implements trait natively (zero serialization, e.g. grid-runtime)
    T2 Aligned   — implements via gRPC adapter (e.g. hermes-runtime-python, claude-code-runtime-python)
    T3 Framework — external agent framework wrapped by adapter

    ── 12 MUST methods (certifier verifies presence + passing tests) ──
    """

    def Initialize(self, request, context):
        """Start a session with a structured v2 SessionPayload (P1-P5 blocks).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Send a user message; stream back incremental response chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSkill(self, request, context):
        """Load a skill into the current session (merges into P4).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnToolCall(self, request, context):
        """Pre-tool-use hook ingestion point.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnToolResult(self, request, context):
        """Post-tool-use hook ingestion point.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnStop(self, request, context):
        """Stop hook ingestion (agent produced final answer).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Serialize session state for persistence / handoff.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectMCP(self, request, context):
        """Connect to one or more MCP servers for this session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitTelemetry(self, request, context):
        """Emit structured telemetry (tokens used, cost, latency, memory candidates).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Return runtime capability manifest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Gracefully terminate the session (emit POST_SESSION_END).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreState(self, request, context):
        """Restore a previously serialized session state (MUST per v2.0 spec).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """── 4 OPTIONAL methods (cert reports as bonus, not failure if absent) ──

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitEvent(self, request, context):
        """── OPTIONAL — ADR-V2-001 Accepted (Phase 1) ──

        EmitEvent exposes the session's emergent event stream to L4.
        OPTIONAL: T1 runtimes SHOULD implement to emit enriched events
        (THINKING, TOKEN_USAGE, PRE_COMPACT). Core events (PRE_TOOL_USE,
        POST_TOOL_USE, STOP) are captured by L4 platform interceptor.
        Default: no-op (return Empty).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.InitializeRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.InitializeResponse.SerializeToString,
            ),
            'Send': grpc.unary_stream_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.SendRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.SendResponse.SerializeToString,
            ),
            'LoadSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSkill,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.LoadSkillRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.LoadSkillResponse.SerializeToString,
            ),
            'OnToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.OnToolCall,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolCallEvent.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolCallAck.SerializeToString,
            ),
            'OnToolResult': grpc.unary_unary_rpc_method_handler(
                    servicer.OnToolResult,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolResultEvent.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolResultAck.SerializeToString,
            ),
            'OnStop': grpc.unary_unary_rpc_method_handler(
                    servicer.OnStop,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StopEvent.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StopAck.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.SerializeToString,
            ),
            'ConnectMCP': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectMCP,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ConnectMCPRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ConnectMCPResponse.SerializeToString,
            ),
            'EmitTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitTelemetry,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.TelemetryRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.Capabilities.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            ),
            'RestoreState': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreState,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.HealthResponse.SerializeToString,
            ),
            'DisconnectMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectMcp,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.DisconnectMcpRequest.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            ),
            'PauseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSession,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.SerializeToString,
            ),
            'ResumeSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSession,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            ),
            'EmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitEvent,
                    request_deserializer=eaasp_dot_runtime_dot_v2_dot_runtime__pb2.EventStreamEntry.FromString,
                    response_serializer=eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eaasp.runtime.v2.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eaasp.runtime.v2.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """============================================================
    EAASP v2.0 — L1 Runtime Contract
    ============================================================

    Spec: docs/design/EAASP/EAASP-Design-Specification-v2.0.docx §8

    16 methods total:
    - 12 MUST (certified core, every conforming runtime implements)
    -  4 OPTIONAL (health / pause / disconnect / resume)
    -  1 PLACEHOLDER (EmitEvent — ADR-V2-001 pending)

    Runtime tiers:
    T1 Harness   — implements trait natively (zero serialization, e.g. grid-runtime)
    T2 Aligned   — implements via gRPC adapter (e.g. hermes-runtime-python, claude-code-runtime-python)
    T3 Framework — external agent framework wrapped by adapter

    ── 12 MUST methods (certifier verifies presence + passing tests) ──
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/Initialize',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.InitializeRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/Send',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.SendRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/LoadSkill',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.LoadSkillRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.LoadSkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/OnToolCall',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolCallEvent.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolCallAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnToolResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/OnToolResult',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolResultEvent.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ToolResultAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/OnStop',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StopEvent.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StopAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/GetState',
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectMCP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/ConnectMCP',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ConnectMCPRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.ConnectMCPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/EmitTelemetry',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.TelemetryRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/GetCapabilities',
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/Terminate',
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/RestoreState',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/Health',
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/DisconnectMcp',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.DisconnectMcpRequest.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/PauseSession',
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/ResumeSession',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.StateResponse.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eaasp.runtime.v2.RuntimeService/EmitEvent',
            eaasp_dot_runtime_dot_v2_dot_runtime__pb2.EventStreamEntry.SerializeToString,
            eaasp_dot_runtime_dot_v2_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
